### ISSUE TITLE
vr bindings do not work on index

### ISSUE THREAD

**Issue by NotAKidOnSteam** [NotAKidOnSteam/PickupPushPull#4]
built in vr binds do not work on knuckls controllers, assuming touch input isn't enabled by default in steamvr bindings

damn

**Comment by ShaunDreclin** [comment]
Same issue here, tried using this mod with index controllers and it just doesn't seem to do anything

**Comment by NotAKidOnSteam** [comment]
I can provide a SteamVR binding as alternative, or possibly read a certain Index finger combo to enable rotation. 

I do not own knuckles controllers so it's a bit hard to know what feels comfortable or test what works.

**Comment by ShaunDreclin** [comment]
A steamvr binding would probably work best

**Comment by NotAKidOnSteam** [comment]
i purchased knuckles so i can account for cases like these- ill be updating the mod once I've found a solution that i feel isn't shit and nice to use

**Comment by NotAKidOnSteam** [comment]
well the fix is to just manually bind the missing steamvr bindings that chillouts defaults dont

Controller Button A Touch
Controller Button B Touch
Controller Stick Touch
Controller Trigger Touch
ect

for each hand...
